FROM python:3.10-slim

RUN apt-get update && apt-get install -y && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

WORKDIR /api

COPY . /api/

RUN pip install -r /api/requirements.txt

CMD ["python3", "app.py"]